# Recipe for Swift - The Swift Programming Language
# Based on Fedora 41's Swift 6.0.3-RELEASE build
# See: https://koji.fedoraproject.org/koji/buildinfo?buildID=2602564

context:
  name: swift
  version: "6.0.3"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # Main Swift repository
  - url: https://github.com/apple/swift/archive/refs/tags/swift-${{ version }}-RELEASE.tar.gz
    sha256: eef9f312d00540cfabc35cb1da9221dd15d3aaca546497a14f29a641ee6484e3
    target_directory: swift
    patches:
      - patches/0001-Use-ldd-instead-of-gold.patch

build:
  skip:
    - not linux
  script: build.sh
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - clangxx
    - clang
    - cmake <4
    - ninja
    - git
    - patch
    - make
    - bash
    # Python removed the `pipes` module in 3.13 which is used, so we need to use 3.12.
    - python 3.12.*
  host:
    - glib
    - glib-tools
    - binutils
    - libstdcxx-ng
    - libgomp
    - libgcc-ng
    - libxml2
    - sqlite
    - ncurses
    - libedit
    - swig
    - rsync
    - curl

tests:
  - script:
    - swift --version
    - swift --help

about:
  homepage: https://swift.org
  summary: 'The Swift Programming Language'
  description: |
    Swift is a high-performance system programming language. It has a clean and modern syntax,
    offers seamless access to existing C and Objective-C code and frameworks, and is memory-safe by default.

    Swift is a complete and independent language that packages core features like flow control,
    data structures, and functions, with high-level constructs like objects, protocols, closures, and generics.
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://swift.org/documentation/
  repository: https://github.com/swiftlang/swift

extra:
  recipe-maintainers:
    - jjerphan
